Feature, configurable network port
Significant-Gravitas/AutoGPT pull request #6678
Opened 2024-01-06 15:15 UTC by lukolszewski

### Background

This implements a configurable network port. I often have other stuff running locally on port 8000 and I wanted to be able to change this default.

### Changes 🏗️

This only adds a config option named serving_port which reads the environment variable PORT, if this is not present it defaults to 8000.

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [x] Have you changed or added a feature? &ensp; `-4 pts`
- [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
- [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
- [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-01-12 10:09 UTC, Pwuts requested changes
Thanks for the useful proposal! Please see the comments above/below:

2024-01-12 10:09 UTC, Pwuts commented on cli.py
> +        pids = subprocess.check_output(["lsof", "-t", "-i", ":"+str(agent_port)]).split()
```suggestion
        pids = subprocess.check_output(["lsof", "-t", "-i", f":{agent_port}"]).split()
```

2024-01-12 10:09 UTC, Pwuts commented on cli.py
>          click.echo("No process is running on port 8000")
```suggestion
        click.echo(f"No process is running on port {agent_port}")
```

2024-01-12 10:09 UTC, Pwuts commented on autogpts/autogpt/autogpt/config/config.py
> +    )
This should be in the "Application Settings" section, e.g. on line 55. Also, can you rename `agent_port` to `serve_port` or `agent_serve_port`?

2024-01-12 10:09 UTC, Pwuts commented on autogpts/autogpt/run
> +kill $(lsof -t -i :${AGENT_PORT:-8080})
1. This should default to 8000 like it does now
2. This will break the benchmark when `AGENT_PORT` is not set to its default, because AGBenchmark uses the `host` property (including port) from `agbenchmark_config/config.json` to connect to the subject agent's API.

2024-01-12 10:09 UTC, Pwuts commented on run
> +python3 cli.py "$@"
Missing `\n`

2024-01-12 10:09 UTC, Pwuts commented on run
> +source .env
For most users, `.env` does not exist and this shows a warning.

2024-01-12 10:09 UTC, Pwuts commented on autogpts/autogpt/run_benchmark
AGBenchmark reads `PORT`, not `BENCHMARK_PORT`:

https://github.com/Significant-Gravitas/AutoGPT/blob/25cc6ad6ae651c3b925ab9447421337c2f4b68e1/benchmark/agbenchmark/__main__.py#L191-L193

2024-01-12 10:09 UTC, Pwuts commented on autogpts/autogpt/autogpt/app/main.py
> +    await server.start(port=config.serving_port)
does not match the config attribute created in config.py

2024-01-12 13:43 UTC, Pwuts commented
Just merged #6569 which makes the port configurable but doesn't touch the `run` and `run_benchmark` scripts etc. If you address the comments and resolve the conflict this can still be merged.

2024-06-28 11:31 UTC, closed without merging

2024-06-28 21:54 UTC, Swiftyos commented
Closed due to a lack of activity. If you want to pick this up again, let me know and we can reopen