Update the forge to have a very very bad, but "functional" agent by default
Significant-Gravitas/AutoGPT pull request #7021
Opened 2024-03-17 05:36 UTC by ntindle

### Background

### Changes 🏗️

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-03-17 05:40 UTC, ntindle commented on autogpts/forge/forge/sdk/model.py
> -        json_encoders={datetime: lambda v: v.isoformat()},
This is why the openapi docs doesn't work btw

2024-03-17 05:40 UTC, ntindle commented on autogpts/forge/forge/sdk/prompting.py
> +            template = template.replace("\\", "/")
windows compat

2024-03-17 05:41 UTC, ntindle commented on autogpts/forge/forge/actions/file_system/files.py
> +        ActionParameter(
type fix

2024-03-17 05:41 UTC, ntindle commented on autogpts/forge/forge/actions/file_system/files.py
> +async def list_files(agent: Agent, task_id: str, path: str) -> List[str]:
type hint

2024-03-17 05:42 UTC, ntindle commented on autogpts/forge/forge/actions/registry.py
> +    import asyncio
swifty removal and replacement with more amenable action to not actually having an agent seeded. list_files requires a full agent to be able to be pulled in to actually work

2024-03-17 05:42 UTC, ntindle commented on autogpts/forge/forge/actions/web/web_selenium.py
> +        msg = "An error occurred while trying to load the page"
type fix

2024-03-17 05:43 UTC, ntindle commented on autogpts/forge/forge/agent.py
> +        # return step
this is from the tutorial so left here, but replaced with something that "can" work. Its bad at responding though. Could really use some help on the prompts to maek this work sometimes

2024-03-17 05:43 UTC, ntindle commented on autogpts/forge/forge/sdk/__init__.py
> +# from forge.llm import chat_completion_request, create_embedding_request, transcribe_audio
Circular import fix. 

Why do we need this file?

2024-03-17 05:44 UTC, ntindle commented on autogpts/forge/forge/sdk/agent.py
> +        that the agent should perform on one step. Override this method in the ForgeAgent class.
Pointer for users of this to look in the right place

2024-03-17 05:45 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +    return {"message": "Welcome to the AutoGPT Forge"}
Type fix. Pydantic will turn into a response automatically

2024-03-17 05:45 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +    agent: Agent = request["agent"]
Type hinting throughout the file

2024-03-17 05:46 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +        return task_request
pydantic and fastapi will handle the conversions

2024-03-17 05:46 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +            detail=json.dumps(
pydantic prefers raise over response

2024-03-17 05:46 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +    page_size: Optional[int] = Query(default=10, ge=1, alias="pageSize"),
type hints

2024-03-17 05:46 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +        steps = await agent.list_steps(task_id, page or 1, page_size or 10)
type error fix

2024-03-17 05:46 UTC, ntindle commented on autogpts/forge/forge/sdk/routes/agent_protocol.py
> +            step = StepRequestBody(name=None, input="y")
type error fix

2024-04-07 21:12 UTC, Pwuts submitted a review, later dismissed
Looks good overall

2024-04-07 21:12 UTC, Pwuts commented on autogpts/forge/forge/sdk/prompting.py
> +            template = template.replace("\\", "/")
Why needed for Windows compat? Do you know of `Path.as_posix()`?

2024-04-07 21:12 UTC, Pwuts commented on autogpts/forge/forge/agent.py
>  from forge.actions import ActionRegister
Improper formatting

2024-04-23 14:17 UTC, CodiumAI-Agent commented
## PR Review

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, because the PR includes a wide range of changes across multiple files and functionalities, including updates to action definitions, file operations, and agent behavior. The complexity and breadth of these changes require a thorough review to ensure that all modifications are correct and do not introduce new issues.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> 🔍&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The new agent loop might not handle exceptions properly, leading to unhandled exceptions if the JSON response from `chat_completion_request` is malformed or if the action execution fails.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> The use of synchronous file operations in an asynchronous context could lead to blocking behavior and reduce the efficiency of the application.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>autogpts/forge/forge/__main__.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider removing the placeholder ASCII art added in the main file, as it does not contribute to the functionality and clutters the codebase. [important]

</strong>
</td></tr><tr><td>relevant line</td><td></td></tr></table><hr>

<table><tr><td>relevant file</td><td>autogpts/forge/forge/actions/file_system/files.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Replace the synchronous file operations with asynchronous versions to avoid blocking the event loop in an async environment. This change will improve the performance and responsiveness of the application. [important]

</strong>
</td></tr><tr><td>relevant line</td><td>return agent.workspace.list(task_id=task_id, path=str(path))</td></tr></table><hr>

<table><tr><td>relevant file</td><td>autogpts/forge/forge/agent.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Implement error handling for JSON parsing and action execution within the `execute_step` method to prevent the agent from crashing due to unexpected exceptions. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Significant-Gravitas/AutoGPT/pull/7021/files#diff-b73d2260588f4094f6abcf2cd29a31ccb1fb7f2aaf61fd3fb036fa5859496770R176'>chat_response = await chat_completion_request(**chat_completion_kwargs)</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>autogpts/forge/forge/actions/registry.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Ensure cross-platform compatibility by handling path separators correctly when registering actions. The current replacement might not cover all edge cases. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/Significant-Gravitas/AutoGPT/pull/7021/files#diff-6dfa7a9fdb1132f00b13545ae77e3a76c807eb66920361b9a0a66f36c0755c46R117'>.replace("\\", "/")</a></td></tr></table><hr>

</details><hr>

<details> <summary><strong>✨ Review tool usage guide:</strong></summary><hr> 

**Overview:**
The `review` tool scans the PR code changes, and generates a PR review which includes several types of feedbacks, such as possible PR issues, security threats and relevant test in the PR. More feedbacks can be [added](https://pr-agent-docs.codium.ai/tools/review/#general-configurations) by configuring the tool.

The tool can be triggered [automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) every time a new PR is opened, or can be invoked manually by commenting on any PR.
- When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L23) related to the review tool (`pr_reviewer` section), use the following template:
```
/review --pr_reviewer.some_config1=... --pr_reviewer.some_config2=...
```
- With a [configuration file](https://pr-agent-docs.codium.ai/usage-guide/configuration_options/), use the following template:
```
[pr_reviewer]
some_config1=...
some_config2=...
```
    

See the review [usage page](https://pr-agent-docs.codium.ai/tools/review/) for a comprehensive guide on using this tool.


</details>

2024-05-03 15:44 UTC, Pwuts requested changes
Application [crashes when the LLM picks a non-existent command](https://github.com/Significant-Gravitas/AutoGPT/actions/runs/8930811580/job/24531663813?pr=7021#step:5:631), which is also why it fails CI

2024-08-07 08:32 UTC, Swiftyos commented
@ntindle closing this now as too much has changed since it was made

2024-08-07 08:32 UTC, closed without merging