[DRAFT] Add code validation
Significant-Gravitas/AutoGPT pull request #7142
Opened 2024-05-10 14:44 UTC by majdyz

### Background

### Changes 🏗️

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-05-10 15:20 UTC, ntindle commented
Should this be in forge??

2024-05-15 15:21 UTC, majdyz commented on autogpts/autogpt/autogpt/agents/__init__.py
> +from .prompt_strategies.one_shot import OneShotAgentActionProposal
OneShotAgentActionProposal is not part of .agent

2024-05-15 15:22 UTC, majdyz commented on autogpts/autogpt/autogpt/agents/agent.py
> +        prompt_strategy_class: type[PromptStrategy] = CodeFlowAgentPromptStrategy,
decouple agent.py & OneShot. pass this class for custom prompt strategy

2024-05-15 15:23 UTC, majdyz commented on autogpts/autogpt/autogpt/agents/prompt_strategies/code_flow.py
> +        available_functions = {
This is for the generated code validation.

2024-05-15 15:24 UTC, majdyz commented on autogpts/autogpt/autogpt/app/cli.py
> +from dotenv import load_dotenv
Ignore this, for debugging purpose, will revert

2024-05-15 15:26 UTC, majdyz commented on autogpts/autogpt/autogpt/commands/execute_code_flow.py
> +class CodeFlowExecutionComponent(CommandProvider):
So... BaseAgentActionProposal use `use_tool` which only executes a single tool, and it's already intertwined with the agent implementation. So my approach on having this code flow execution is by returning `BaseAgentActionProposal` that use this newly created tool, which is basically executing python code using already existing other tools as variables.

2024-05-15 15:27 UTC, majdyz commented on autogpts/autogpt/autogpt/core/resource/model_providers/schema.py
> +    def fmt_header(self, callable=None) -> str:
callable part here is unused, will revert

2024-05-15 15:44 UTC, majdyz commented on autogpts/autogpt/autogpt/core/resource/model_providers/openai.py
> +                    if isinstance(parsed_result, Coroutine):
So `completion_parser` needs to be async for the code validation, I did this instead of changing the whole usage of it to async.

2024-06-05 12:59 UTC, kcze requested changes
Ok in general but I think it's unclear what this does (please update the description). This introduces new prompt strategy and new `CommandProvider` component. Also missing newlines at the end in multiple files.

2024-06-05 12:59 UTC, kcze commented on autogpt/autogpt/agents/agent.py
> +        self.code_flow_executor.set_available_functions(self.commands)
This approach requires the user to explicitly pass commands.
I think it's better to take commands *from* the agent as opposed to the current *to* the component. You could for example pass `Agent` (or some getter) to the component `__init__` and then just access `commands` when required.

2024-06-05 12:59 UTC, kcze commented on forge/forge/components/code_flow_executor/code_flow_executor.py
Nice to see somebody making a component! :)

2024-06-05 12:59 UTC, kcze commented on autogpt/pyproject.toml
> +ptyprocess = "^0.7.0"
unsorted, should be alphabetical

2024-06-05 12:59 UTC, kcze commented on forge/forge/utils/function/code_validation.py
1. imo files in `forge/utils/function` deserve their own forge-level directory, say `forge/code_execution`.
2. Why not just executing code directly, what this all do?

2024-06-05 12:59 UTC, kcze commented on forge/forge/command/command.py
> +        return type.__name__
This declares return as `type` but returns `str`

2024-06-05 12:59 UTC, kcze commented on forge/forge/components/code_flow_executor/code_flow_executor.py
> +        self._enabled = True
Components are enabled by default

2024-06-05 12:59 UTC, kcze commented on forge/forge/components/code_flow_executor/code_flow_executor.py
> +        yield self.execute_code_flow
This includes `execute_code_flow` in `self.available_functions`, is that intended?
1. Commands are taken from all `CommandsProviders` (including `execute_code_flow`)
2. You pass all commands from agents to the `self.available_functions`
Just remove `execute_code_flow` from `self.available_functions`.

2024-06-05 12:59 UTC, kcze commented on autogpt/autogpt/agents/prompt_strategies/code_flow.py
> +            # "simple strategies with no legal complications.",
I think remove if unused

2024-06-10 05:41 UTC, majdyz commented on forge/forge/utils/function/code_validation.py
It validates the code using static code analysis, and passes an error message to retry, if any.

2024-06-10 05:48 UTC, majdyz commented on autogpt/autogpt/agents/agent.py
> +        self.code_flow_executor.set_available_functions(self.commands)
I don't get it, so the component will depends on agent?
Now you need to build an agent to simply execute a component, and won't this also create a circular dependency?

2024-06-10 10:45 UTC, kcze commented on autogpt/autogpt/agents/agent.py
> +        self.code_flow_executor.set_available_functions(self.commands)
You are right, it's a bad idea to pass `Agent`, just pass a method/lambda instead:
```py
    # agent.py
    # __init__
    self.code_flow_executor = CodeFlowExecutionComponent(get_commands)

    def get_commands(self) -> list[Command]:
        return self.commands
```
So you don't need to call `set_available_functions` in agent classes - it's the component responsibility and dev shouldn't worry about calling anything extra just so the component works.

2024-06-27 21:54 UTC, ntindle commented
What’s left on this?

2024-07-02 15:35 UTC, Swiftyos approved these changes

2024-10-14 15:28 UTC, aarushik93 commented
@majdyz  can I close this PR, seems we're not working on it?

2024-10-15 22:23 UTC, Pwuts commented
This could be a really awesome block

2024-10-16 06:02 UTC, majdyz commented
@aarushik93 sure I'll close it.
@Pwuts this could be a nice block if we managed to circumvent the security vulnerability. not sure if limiting the scope & package that can be used is secure enough or it's still going to prone to ddos & CVE.

2024-10-16 06:02 UTC, closed without merging