Fix poetry install issue on ARM64 & python 3.12
Significant-Gravitas/AutoGPT pull request #7145
Opened 2024-05-11 10:36 UTC by majdyz

### Background

Thinc (the inferred dependency of spacy & en-core-web-sm) 8.1.12 is broken on Arm64: https://github.com/explosion/thinc/issues/474.
The scope of this change is to upgrade the existing deps to not use the older version of Thinc to fix the issue.

This should fix:
https://github.com/Significant-Gravitas/AutoGPT/issues/7132
https://github.com/Significant-Gravitas/AutoGPT/issues/7111
https://github.com/Significant-Gravitas/AutoGPT/issues/7080
https://github.com/Significant-Gravitas/AutoGPT/issues/6597

### Changes 🏗️

Upgraded `en-core-web-sm` to 3.7.1 and `spacy` to 3.7.4.

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [x] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-05-11 10:42 UTC, ntindle submitted a review, later dismissed

2024-05-13 21:26 UTC, Pwuts requested changes

2024-05-13 21:26 UTC, Pwuts commented on autogpts/autogpt/poetry.lock
Please revert and run `poetry lock` again with `--no-update`

2024-05-14 14:10 UTC, ntindle approved these changes

2024-05-14 14:10 UTC, merged