Aarushikansal/open 1519 create migrations db
Significant-Gravitas/AutoGPT pull request #7513
Opened 2024-07-20 11:12 UTC by aarushik93

### Background

### Changes 🏗️

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-07-21 17:14 UTC, aarushik93 commented
Based on the discussions on discord regarding DB engines and ORMs, I'm making this a draft PR so it doesn't accidentally get merged

2024-07-22 14:44 UTC, aarushik93 commented on rnd/autogpt_server/migrations/migration_lock.toml
> +# Please do not edit this file manually
Added the SQLite migrations, given we are dropping installer support right now.

2024-07-22 14:58 UTC, Swiftyos requested changes

2024-07-22 14:58 UTC, Swiftyos commented on rnd/autogpt_server/README.md
> +
Can you update the README to include details on `PRISMA_SCHEMA_PATH` please

2024-07-22 14:58 UTC, Swiftyos approved these changes

2024-07-22 15:57 UTC, ntindle approved these changes
Would be cool to check in ci if there’s the same number of migrations for both

2024-07-22 18:05 UTC, ntindle approved these changes

2024-07-22 22:43 UTC, merged