Feat(Builder): Super early version of the discord bots blocks
Significant-Gravitas/AutoGPT pull request #7670
Opened 2024-08-01 18:23 UTC by Bentlybro

### Background

This is a super early version of discord bot blocks

### Changes 🏗️

Added a file ``discordblocks.py`` which contains the code

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-08-01 18:54 UTC, Bentlybro commented
test

2024-08-02 19:57 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/blocks/discordblock.py
> +        username: str  # The username of the user who sent the message
aside: can we use Field() to have these populate with descriptions on the frontend?

2024-08-02 19:58 UTC, ntindle requested changes

2024-08-02 19:58 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/util/settings.py
>      model_config = SettingsConfigDict(
update env template

2024-08-02 21:04 UTC, ntindle requested changes

2024-08-02 21:04 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/blocks/discordblock.py
> +        message_content: str  # The content of the message to send
swap the order of these so they match the other one 
![image](https://github.com/user-attachments/assets/2bbea07f-3abf-4651-931a-5b06680c4d6d)

2024-08-02 21:18 UTC, ntindle approved these changes

2024-08-02 21:21 UTC, merged