feat(builder): Add ControlPanel and Separator components
Significant-Gravitas/AutoGPT pull request #7680
Opened 2024-08-02 20:10 UTC by andrewhooker2

### Background
This PR aims to add UI components for an upcoming UI / UX update for our Agent Editor.
Introduced a new `ControlPanel` component that displays a panel with control icons and child components. Added a `Separator` component from Radix UI to differentiate sections within the control panel. Updated dependencies accordingly.

### Changes 🏗️

- Added a  `ControlPanel` component that displays a panel with control icons and child components. 
- Added a `Separator` component from ShadCn's Radix UI to differentiate sections within the control panel. Updated dependencies accordingly.

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [ ] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [ ] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-08-02 20:43 UTC, ntindle approved these changes

2024-08-02 20:51 UTC, ntindle requested changes
Thanks for the contribution! This will look much better, make sure you link the issue, add screenshots, and stack on top with actual implementation

2024-08-02 22:45 UTC, andrewhooker2 commented
@ntindle  Thank you for mentioning that I have linked the issue here. I'll also link it in the subsequent PR's as well.

2024-08-05 04:38 UTC, ntindle approved these changes

2024-08-05 04:38 UTC, merged