fix(github): Update CODEOWNERS for rnd directories
Significant-Gravitas/AutoGPT pull request #7684
Opened 2024-08-02 21:42 UTC by andrewhooker2

### Background
We have added a new project with the directory `rnd/` containing several subdirectories. This PR updates the CODEOWNERS file to include maintainers for these new directories, ensuring proper code ownership and review processes.

### Changes 🏗️
- Updated the CODEOWNERS file in the `.github` directory to include new entries for the `rnd/` subdirectories.
- Added a new maintainer group `@Significant-Gravitas/rnd-maintainers` for the new project.
- Assigned the new maintainer group to all subdirectories of `rnd/` except for `infra/`.

### PR Quality Scorecard ✨
- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-08-02 21:49 UTC, Torantulino commented
> **Maintainability**	
> Consolidate multiple `rnd/` directory entries into a single wildcard entry
> **Consolidate the entries for the `rnd/` subdirectories under a single pattern to simplify the CODEOWNERS file and make future maintenance easier. This avoids redundancy and potential errors in future updates.**
> 
> [.github/CODEOWNERS [6-10]](https://github.com/Significant-Gravitas/AutoGPT/pull/7684/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R6-R10)
> 
> ```diff
> -rnd/auto-gpt_builder/  @Significant-Gravitas/rnd-maintainers
> -rnd/autogpt_libs/      @Significant-Gravitas/rnd-maintainers
> -rnd/autogpt_server/    @Significant-Gravitas/rnd-maintainers
> -rnd/example_files/     @Significant-Gravitas/rnd-maintainers
> -rnd/market/            @Significant-Gravitas/rnd-maintainers
> +rnd/*  @Significant-Gravitas/rnd-maintainers
>  
> ```
> 
> * [ ]  **Apply this suggestion**
> 
> Suggestion importance[1-10]: 9
> Why: The suggestion to consolidate the entries for the `rnd/` subdirectories into a single wildcard entry improves maintainability by reducing redundancy and minimizing potential errors in future updates. The existing code is correctly identified, and the improved code accurately reflects the suggestion.
> 
> 9

Would this produce the same result?

2024-08-02 21:50 UTC, ntindle requested changes

2024-08-02 21:50 UTC, ntindle commented on .github/CODEOWNERS
> +rnd/market/            @Significant-Gravitas/rnd-maintainers
Love the idea, use maintainers without rnd- though

2024-08-02 21:51 UTC, ntindle commented
> > **Maintainability**
> > Consolidate multiple `rnd/` directory entries into a single wildcard entry
> > **Consolidate the entries for the `rnd/` subdirectories under a single pattern to simplify the CODEOWNERS file and make future maintenance easier. This avoids redundancy and potential errors in future updates.**
> > [.github/CODEOWNERS [6-10]](https://github.com/Significant-Gravitas/AutoGPT/pull/7684/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R6-R10)
> > ```diff
> > -rnd/auto-gpt_builder/  @Significant-Gravitas/rnd-maintainers
> > -rnd/autogpt_libs/      @Significant-Gravitas/rnd-maintainers
> > -rnd/autogpt_server/    @Significant-Gravitas/rnd-maintainers
> > -rnd/example_files/     @Significant-Gravitas/rnd-maintainers
> > -rnd/market/            @Significant-Gravitas/rnd-maintainers
> > +rnd/*  @Significant-Gravitas/rnd-maintainers
> >  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Suggestion importance[1-10]: 9
> > Why: The suggestion to consolidate the entries for the `rnd/` subdirectories into a single wildcard entry improves maintainability by reducing redundancy and minimizing potential errors in future updates. The existing code is correctly identified, and the improved code accurately reflects the suggestion.
> 
> Would this produce the same result?

We also have infra in there that should be under devops probs

2024-08-02 22:08 UTC, ntindle commented
@Torantulino made me think about it and they run top to bottom so defining a root * one works and then overwriting with infra

2024-08-02 22:19 UTC, ntindle commented on .github/CODEOWNERS
> +frontend/ @Significant-Gravitas/frontend-maintainers
this is an existing bug, they don't have write access to the repo

2024-08-02 22:19 UTC, ntindle approved these changes

2024-08-02 22:22 UTC, ntindle approved these changes

2024-08-02 22:23 UTC, merged

2024-08-03 00:35 UTC, ntindle commented
Fixed #7683