tweak(rnd): Trim Whitespace from BlockSecret to Prevent Authentication Issues
Significant-Gravitas/AutoGPT pull request #7789
Opened 2024-08-12 11:18 UTC by voulkon

### Background

When users are prompted to input their API key, there is a possibility that they might include extra whitespace, particularly if they copy and paste the key from an environment file or another source. 
This extra whitespace could include leading or **trailing spaces**, or even **newline characters**, which could result in the API key being rejected by the system or causing unexpected behavior.

![Error-Caused-from-User-Input](https://github.com/user-attachments/assets/19a4194b-05ec-4be1-bfed-545955366bfd)

### Changes 🏗️

Added on the `BlockSecret` class the functionality to return the api key trimmed, detecting each time whether it's actually needed to intervene and alter it and informing accordingly with a short `logger.debug` message.

![corrected](https://github.com/user-attachments/assets/b89c93f8-146f-4ec8-a730-dae426452f4d)

### PR Quality Scorecard ✨

- [x] Have you used the PR description template? &ensp; `+2 pts`
- [x] Is your pull request atomic, focusing on a single change? &ensp; `+5 pts`
- [ ] Have you linked the GitHub issue(s) that this PR addresses? &ensp; `+5 pts`
- [x] Have you documented your changes clearly and comprehensively? &ensp; `+5 pts`
- [ ] Have you changed or added a feature? &ensp; `-4 pts`
  - [ ] Have you added/updated corresponding documentation? &ensp; `+4 pts`
  - [ ] Have you added/updated corresponding integration tests? &ensp; `+5 pts`
- [ ] Have you changed the behavior of AutoGPT? &ensp; `-5 pts`
  - [ ] Have you also run `agbenchmark` to verify that these changes do not regress performance? &ensp; `+10 pts`

2024-08-13 15:44 UTC, ntindle requested changes
Should this happen on the frontend?

2024-08-13 15:44 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/data/model.py
> +            if value != trimmed_value:
We probably don’t want to log the actual values as they’re secrets

2024-08-13 15:44 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/data/model.py
> +            trimmed_value = value.strip()
Is this whole segment needed here?

2024-08-13 15:44 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/data/model.py
> +            logger.debug(f"Trimming value from '{self._value}' to '{trimmed_value}'")
Don’t log the values, just that it occurred

2024-08-13 15:44 UTC, ntindle commented on rnd/autogpt_server/autogpt_server/data/model.py
> +            logger.info(f"Trimming value from '{self._value}' to '{trimmed_value}'")
Don’t log the values just that it occured

2024-08-14 09:38 UTC, voulkon commented on rnd/autogpt_server/autogpt_server/data/model.py
> +            if value != trimmed_value:
Totally agree.
I just saw the api key printed in the `execute with input:` stage (see screenshot above) and thought "apparently we print secrets, that's a risk we embrace".
I'll remove it.

2024-08-21 10:22 UTC, Swiftyos commented
@voulkon This is super useful and we'd like it merged fairly soon. Do you think you will get a chance to make the requested changes soon?

2024-08-21 15:37 UTC, voulkon commented on rnd/autogpt_server/autogpt_server/data/model.py
> +            trimmed_value = value.strip()
Do you mean attempting to alter the `self._value` attribute instead of the `get_secret_value` method only?

For this, I thought that **someone sometime might try to access the `self._value` immediately** instead of using the `self.get_secret_value()` and wanted to make sure it would be appropriate.

There's also a chance you mean repeating the whole process of trimming the value and assigning it to the `self._value` for both the scenario _where a value is provided_ (`value is not None`) and the one _where it is retrieved_ with the `self.__get_secret(key)` method.

Either case, I hated repeating myself. 
Do you think keeping the whole trimming logic into the `get_secret_value` method would suffice?

2024-08-21 15:49 UTC, voulkon commented
Hi @Swiftyos and @Torantulino,

@ntindle's review provided : 

Two questions for (possible) redundancy: 
1. whether this whole process is backend's responsibility and 
2. whether we should take care to alter the `self._value`, since it's intended for internal use only.

One actionable change: 

- stop logging actual secret values

I dealt with the last one on my last commit: c52a1c5

Regarding the redundancies, they do exist, but it doesn't hurt to be extra safe.

2024-08-21 16:02 UTC, voulkon reviewed
Transmitting the secret trimmed is indeed frontend's responsibility.

But for better or worse, backend should be able to handle un-trimmed values itself (as a secondary line of defense on user's behavior).

2024-08-21 19:44 UTC, ntindle approved these changes

2024-08-21 19:44 UTC, merged