Added new Multimodal AI Block utilizing openrouter's API Service.
Significant-Gravitas/AutoGPT pull request #8290
Opened 2024-10-10 13:55 UTC by ymrohit

This PR introduces the MultimodalAIBlock class, a new block that integrates multimodal AI models via OpenRouter API. It allows users to input a text prompt and an image URL, and select from several multimodal models for analysis. The block processes the inputs and returns a response based on the selected AI model.

2024-10-10 13:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Significant-Gravitas/AutoGPT?pullRequest=8290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Significant-Gravitas/AutoGPT?pullRequest=8290) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: Torantulino<br/>:white_check_mark: majdyz<br/>:x: ymrohit<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Significant-Gravitas/AutoGPT?pullRequest=8290) it.</sub>

2024-10-16 15:13 UTC, aarushik93 commented
thanks for the PR @ymrohit - just curious there's no speech modality models available via Openrouter as of now right?

2024-10-17 10:03 UTC, ymrohit commented
@aarushik93 I don't think there is any speech modality models available via openrouter at the moment.

2024-10-17 14:19 UTC, aarushik93 approved these changes

2024-11-06 23:44 UTC, aarushik93 commented on autogpt_platform/infra/helm/autogpt-market/values.prod.yaml
> +  DATABASE_URL: "AgCe47Y6QFnZRmNNpc3iVIcJ9zAZMPr/1OU61Slr0oM1yjneT7LgNTrAD9+QSu7Q0q2u+533FImOu8o/pKG0gNzEtyeSEEsegmCiaxs4Wi+/jVodU8CgfrYN3xkgi7QuD2fMs/zz+sv25LDg8LR1mIvkv+W/PkbqoVx3UAUXL7ZM+UvkFqie+6
please remove

2024-11-06 23:45 UTC, aarushik93 commented on autogpt_platform/backend/backend/util/settings.py
> +    openrouter_api_key: str = Field(default="", description="OpenRouter API Key")
Please migrate to new credentials system

2024-11-06 23:45 UTC, aarushik93 requested changes
Please see comments

2024-11-20 19:12 UTC, aarushik93 commented
@ymrohit we've now added OpenRouter to the new platform and so this PR is no longer needed....we'd still love for you to contribute other blocks and integrations 🙏🏽

2024-11-20 19:12 UTC, closed without merging