Merge login and signin
Significant-Gravitas/AutoGPT pull request #8389
Opened 2024-10-22 05:43 UTC by Abhi1992002

### Background

Both the login and signup processes were the same, causing confusion. Now, there’s a single route for login, and if the user isn’t registered, they’ll be redirected to the signup page automatically.

### Changes 🏗️

- Created two separate files for login and signup.

- If a user tries to log in and their email is not found in the system, they will 
   be redirected to the signup page.
         
- If the user is already registered, the usual login process will proceed.

### Testing 🔍

• The login flow to ensure redirection to signup if email is not present.
• Confirmed successful login for registered users.

https://github.com/user-attachments/assets/0a398b4e-d57a-4634-be6c-d4a326fc9792

2024-10-22 05:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Significant-Gravitas/AutoGPT?pullRequest=8389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Significant-Gravitas/AutoGPT?pullRequest=8389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Significant-Gravitas/AutoGPT?pullRequest=8389) it.</sub>

2024-10-22 18:46 UTC, ntindle requested changes
good start, just some quick things. I'll let other team members review the frontend code otherwise

2024-10-22 18:46 UTC, ntindle commented on autogpt_platform/docker-compose.yml
revert these changes, not needed afaik (as far as I know)

2024-10-22 18:46 UTC, ntindle commented on autogpt_platform/supabase
revert this plz

2024-10-22 18:46 UTC, ntindle commented on autogpt_platform/frontend/yarn.lock
I don't think this one is needed

2024-10-23 04:28 UTC, Abhi1992002 commented on autogpt_platform/docker-compose.yml
Done..!!

2024-10-23 04:28 UTC, Abhi1992002 commented
Done..!!

2024-10-23 11:53 UTC, aarushik93 commented
@Abhi1992002 same thing here regarding supabase

2024-10-23 21:12 UTC, ntindle approved these changes

2024-10-23 21:23 UTC, merged