fix: show error toast on Run failure when inputs or credentials are i…
Significant-Gravitas/AutoGPT pull request #8391
Opened 2024-10-22 07:10 UTC by Abhi1992002

### Fixes #8332

## Background

The issue is that when “Run” fails due to invalid inputs (e.g., deleted credentials), no error message is shown in the UI.

### Changes 🏗️

- Added toast notification (variant="destructive") for "Run" failures.
- Displays error when the execution request returns an HTTP 400 due to invalid hard-coded input values 

https://github.com/user-attachments/assets/e5686fcf-e376-40ca-876a-8cb99aec2e2e

2024-10-22 19:46 UTC, ntindle commented on autogpt_platform/supabase
if we revert the change to supabase, this is good to go!

2024-10-22 19:48 UTC, ntindle requested changes
revert supabase change and this is ready after

2024-10-23 04:10 UTC, Abhi1992002 commented
Done..!!

2024-11-08 17:50 UTC, aarushik93 commented
@Abhi1992002 can you fix the tests please and then we can get this in

2024-11-12 01:35 UTC, aarushik93 approved these changes

2024-11-12 04:43 UTC, ntindle approved these changes

2024-11-12 04:43 UTC, merged