Fix/handle empty agents response #8370
Significant-Gravitas/AutoGPT pull request #8393
Opened 2024-10-22 13:21 UTC by Abhi1992002

### Fixes #8370 

I added a check to handle cases where no agents or featured agents are returned from the backend. This prevents the marketplace from crashing due to an undefined property error and ensures the UI still loads properly.

### Changes 🏗️

Added fallback messages for when featuredAgents and topAgents are empty.

<img width="1438" alt="Screenshot 2024-10-22 at 6 45 45 PM" src="https://github.com/user-attachments/assets/fdd49f29-8c6e-4aa0-b6e6-c41c0d4c4c4c">

2024-10-22 19:45 UTC, ntindle requested changes

2024-10-22 19:45 UTC, ntindle commented on autogpt_platform/supabase
revert the supabase change and this should be good to go

2024-10-23 04:06 UTC, Abhi1992002 commented on autogpt_platform/supabase
Done..!!

2024-10-23 11:51 UTC, aarushik93 commented
@Abhi1992002 thanks for this, but the supabase submodule shouldn't be deleted in this PR. Can you please fix that?

2024-10-23 14:37 UTC, aarushik93 approved these changes
LGTM

2024-10-24 16:34 UTC, merged