add: api generator functions and endpoints
Significant-Gravitas/AutoGPT pull request #8597
Opened 2024-11-08 13:06 UTC by Abhi1992002

### Fix #8589 

This issue depends on #8585 

---

These changes make it easy to create and manage API keys, so we can control who gets access and what they can do. It’s like giving out special keys that we can turn on or off anytime, keeping things secure and organized.

### Changes 🏗️

- Created `/api-keys` endpoint to generate a new API key with custom permissions.

- Added `generate_api_key` function to handle API key generation and hashing.

- Built `validate_api_key` function to check if a provided API key is valid.

- Created `DELETE /api-keys/{key_id}` endpoint to revoke an API key.

- Made `POST /api-keys/{key_id}/suspend` and `POST /api-keys/{key_id}/reactivate` endpoints to suspend/reactivate keys.

- Added `list_user_api_keys` function to list all API keys for a user, ordered by creation date.

- Created `update_api_key_permissions` function to modify an existing key’s permissions.

- Defined `request/response models (CreateAPIKeyRequest, CreateAPIKeyResponse)` for API key handling.

- Added permission validation with `has_permission` function to check if a key has the required access.

---

Depends on this schema

```
enum APIKeyPermission {
	EXECUTE_GRAPH // Can execute agent graphs
	READ_GRAPH // Can get graph versions and details
	EXECUTE_BLOCK // Can execute individual blocks
	READ_BLOCK // Can get block information
}

model APIKey {
	id          String             @id @default(uuid())
	name        String
	prefix      String             @unique // First 8 chars for identification
	key         String             @unique // Hashed key
	status      APIKeyStatus       @default(ACTIVE)
	permissions APIKeyPermission[]

	// Core tracking fields
	createdAt  DateTime  @default(now())
	lastUsedAt DateTime?
	revokedAt  DateTime?

	// Basic metadata
	description String?

	// Relation to user
	userId String
	user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)

	@@index([key])
	@@index([prefix])
	@@index([userId])
	@@index([status])
	@@index([userId, status])
}

enum APIKeyStatus {
	ACTIVE
	REVOKED
	SUSPENDED
}
```

2024-11-09 01:09 UTC, aarushik93 commented on autogpt_platform/backend/backend/data/api.py
> +async def reactivate_api_key(key_id: str, user_id: str) -> APIKeyWithoutHash:
We probably don't want to reactivate a key once it's been suspended or revoked

2024-11-09 01:10 UTC, aarushik93 commented on autogpt_platform/backend/backend/util/api_key.py
> +import secrets
Have you seen the autogpt_libs? I think the APIkey helper code can live there

2024-11-09 01:19 UTC, aarushik93 requested changes
@Abhi1992002 thanks for the speedy work as usual

I have a few notes:

We don't need a salt or bcrypt as that's needed for passwords, not for API keys which should already be unique and high entropy strings. So we can use something like token_urlsafe e.g.

secrets.token_urlsafe(32)

for hashing: sha256

We also need a prefix pattern: agpt_<random-string> 

Lastly, in my last PR, I also added a postfix, not sure if you've seen that, would you be able to incorporate that in as well, please

2024-11-09 18:54 UTC, aarushik93 commented on autogpt_platform/autogpt_libs/autogpt_libs/api_key/key_manager.py
> +class APIKeyManager:
thank you for making changes so quickly. 

I think maybe I didn't explain myself clearly enough on the API key generation.

We want to use token_urlsafe to generate the random key: https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe

then we can use hashlib.sha256 to hash the key (and we never store or keep the raw key again). So for example, this class would become something like this: 


```
import secrets
import hashlib

class APIKeyManager:
    PREFIX = "agpt_"
    PREFIX_LENGTH = 8
    POSTFIX_LENGTH = 8

    def generate_api_key(self):
        """Generate a secure API key with agpt_ prefix."""
        raw_key = f"{self.PREFIX}{secrets.token_urlsafe(32)}"
        prefix = raw_key[:self.PREFIX_LENGTH]
        postfix = raw_key[-self.POSTFIX_LENGTH:]
        hashed_key = hashlib.sha256(raw_key.encode()).hexdigest()
        return raw_key, prefix, postfix, hashed_key

    def verify_api_key(self, provided_key: str, stored_hash: str) -> bool:
        """Verify if a provided API key matches the stored hash."""
        return hashlib.sha256(provided_key.encode()).hexdigest() == stored_hash```

2024-11-12 01:16 UTC, aarushik93 reviewed
Looks good, if you can just address a few minor comments and fix the linting then we can merge please

2024-11-12 01:16 UTC, aarushik93 commented on autogpt_platform/backend/backend/server/routers/v1.py
> +class CreateAPIKeyRequest(BaseModel):
These can be moved into model.py

2024-11-12 01:16 UTC, aarushik93 commented on autogpt_platform/backend/backend/data/api.py
> +import uuid
Can we rename the file api_key

2024-11-12 01:16 UTC, aarushik93 commented on autogpt_platform/backend/backend/server/routers/v1.py
> +##################### API ##############################
nit: API KEY

2024-11-12 04:40 UTC, ntindle commented on autogpt_platform/backend/backend/server/routers/v1.py
> +    return await update_api_key_permissions(key_id, user_id, request.permissions)
I think this decorator got detached from its home

2024-11-14 14:33 UTC, merged